#refoss P11
#https://devices.esphome.io/devices/refoss-p11-plug

packages:
  powerplug: !include powerplug-package.yaml

esp8266:
  board: esp01_1m
  restore_from_flash: true

binary_sensor:
  - id: "${devicename}_button_state"
    platform: gpio
    pin:
      number: GPIO05
    on_press:
      if: 
        condition:
          switch.is_off: lock 
        then:
          switch.toggle: button_switch

uart:
  id: cse7766_uart_bus
  rx_pin: GPIO03
  baud_rate: 4800

sensor:
  - platform: adc
    name: "${devicename} - Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    id: temp_analog_reading
    pin: GPIO17
# Uncomment and calibrate based on your device measurements
#    filters:
#      - calibrate_linear:
#        - 0.15 -> 18.6
#        - 0.16 -> 19.8

  - platform: cse7766 # https://esphome.io/components/sensor/cse7766.html
    uart_id: cse7766_uart_bus
    current:
      name: "${devicename} - Current"
      unit_of_measurement: A
      accuracy_decimals: 3
      id: "power_current"
      icon: mdi:current-ac
      filters:
        - throttle_average: 3s
        - calibrate_linear:
          - 0 -> 0.01
          - 7.933 -> 7.930
    energy:
      name: "${devicename} - Energy"
      id: "power_energy"
      unit_of_measurement: Wh
    power:
      name: "${devicename} - Power"
      id: "power_wattage"
      unit_of_measurement: W
      icon: mdi:gauge
      filters:
        - skip_initial: 3
        - throttle_average: 3s
        - calibrate_linear:
          - 0 -> 0.8
          - 957 -> 1798
    voltage:
      id: "power_voltage"
      name: "${devicename} - Voltage"
      unit_of_measurement: V
      accuracy_decimals: 1
      icon: mdi:flash-outline
# Uncomment and calibrate based on your device measurements
      filters:
        - skip_initial: 3
        - throttle_average: 3s
        - calibrate_linear:
          - 0.0 -> 0.0
          - 120.2 -> 224.1
          - 120.4 -> 224.4
          - 121.5 -> 226.4
          - 122.7 -> 227
          - 123.2 -> 229.3
