substitutions:
  devicename: "powerplug02"
  comment: "powerplug Fernseher Schlafzimmer"
  # Higher value gives lower watt readout
  current_res: "0.00280"
  # Lower value gives lower voltage readout
  voltage_div: "775"
  status_led_gpio: GPIO00
  led1_gpio: GPIO02
  relay_gpio: GPIO15

<<: !include ../types/powerplug-sp111.yaml
